{
    'name': 'estate',
    'version': '1.0',
    'license': 'LGPL-3',
    'author': 'Vítor Narciso',
    'category': 'Sales/Real Estate',
    'summary': 'Tutorial module for Real Estate management',
    'description': 'Tutorial module for Real Estate management',
    'depends': ['base'],
    'application': True,
    'installable': True,
    'data': [
        'security/ir.model.access.csv',
        'views/estate_property_views.xml',
        'views/estate_property_offer_views.xml',
        'views/estate_property_type_views.xml',
        'views/estate_property_tag_views.xml',
        'views/res_users_views.xml',
        'views/estate_menus.xml',
    ],
}